In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [16]:
data=pd.read_csv('data.csv')
print(data)

X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

     Outlook  Temperature  Humidity   Wind Play
0      sunny           85        85  False   no
1      sunny           80        90   True   no
2   overcast           83        78  False  yes
3       rain           70        96  False  yes
4       rain           68        80  False  yes
5       rain           65        70   True   no
6   overcast           64        65   True  yes
7      sunny           72        95  False   no
8      sunny           69        70  False  yes
9       rain           75        80  False  yes
10     sunny           75        70   True  yes
11  overcast           72        90   True  yes
12  overcast           81        75  False  yes
13      rain           71        80   True   no


In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [19]:
print(y)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [21]:
print(X_train)

[[1.0 0.0 0.0 83 78 False]
 [0.0 0.0 1.0 75 70 True]
 [0.0 1.0 0.0 68 80 False]
 [0.0 0.0 1.0 80 90 True]
 [1.0 0.0 0.0 81 75 False]
 [0.0 0.0 1.0 85 85 False]
 [0.0 1.0 0.0 71 80 True]
 [0.0 1.0 0.0 75 80 False]
 [0.0 0.0 1.0 69 70 False]
 [1.0 0.0 0.0 72 90 True]
 [0.0 1.0 0.0 65 70 True]]


In [22]:
print(X_test)

[[0.0 1.0 0.0 70 96 False]
 [0.0 0.0 1.0 72 95 False]
 [1.0 0.0 0.0 64 65 True]]


In [23]:
print(y_train)

[1 1 1 0 1 0 0 1 1 1 0]


In [24]:
print(y_test)

[1 0 1]


In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [27]:
print(X_train)

[[1.0 0.0 0.0 1.2867507236248845 -0.12964074471043294 -0.912870929175277]
 [0.0 0.0 1.0 0.014457873299156014 -1.2704792981622424 1.0954451150103324]
 [0.0 1.0 0.0 -1.0987983707358566 0.15556889365251944 -0.912870929175277]
 [0.0 0.0 1.0 0.8096409047527363 1.5816170854672813 1.0954451150103324]
 [1.0 0.0 0.0 0.9686775110434523 -0.5574552022548616 -0.912870929175277]
 [0.0 0.0 1.0 1.6048239362063166 0.8685929895599003 -0.912870929175277]
 [0.0 1.0 0.0 -0.6216885518637083 0.15556889365251944 1.0954451150103324]
 [0.0 1.0 0.0 0.014457873299156014 0.15556889365251944 -0.912870929175277]
 [0.0 0.0 1.0 -0.9397617644451405 -1.2704792981622424 -0.912870929175277]
 [1.0 0.0 0.0 -0.46265194557299216 1.5816170854672813 1.0954451150103324]
 [0.0 1.0 0.0 -1.5759081896080047 -1.2704792981622424 1.0954451150103324]]


In [28]:
print(X_test)

[[0.0 1.0 0.0 70.0 96.00000000000001 8.07434927000114e-17]
 [0.0 0.0 1.0 72.0 95.00000000000001 8.07434927000114e-17]
 [1.0 0.0 0.0 64.0 65.00000000000001 1.0000000000000002]]
